package br.com.lotofacil.perimetro11;
import android.app.*; import android.content.*; import android.net.Uri; import android.os.*; import java.io.*; import java.util.*;
public class AnalysisService extends Service { public static final String PREF="perimetro11_state"; private static final String CHANNEL="perimetro11_channel"; private volatile boolean worker=false;
 @Override public void onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"Lotofácil Perímetro 11",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private Notification note(String text,int pct){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);return b.setContentTitle("Lotofácil Perímetro 11").setContentText(text).setSmallIcon(android.R.drawable.stat_notify_sync).setOngoing(true).setOnlyAlertOnce(true).setProgress(100,Math.max(0,Math.min(100,pct)),false).setContentIntent(pi).build();}
 private void notifyNow(String t,int p){try{getSystemService(NotificationManager.class).notify(71,note(t,p));}catch(Exception ignored){}}
 @Override public int onStartCommand(Intent i,int flags,int id){SharedPreferences sp=getSharedPreferences(PREF,MODE_PRIVATE);if(i!=null&&"START".equals(i.getAction())){String uri=i.getStringExtra("uri");int rep=i.getIntExtra("repeats",-1);if(rep!=8&&rep!=9&&rep!=10){sp.edit().putBoolean("running",false).putString("error","Repetidas inválidas: "+rep).apply();return START_NOT_STICKY;}sp.edit().putString("uri",uri==null?"":uri).putInt("repeats",rep).putBoolean("running",true).putBoolean("done",false).putString("error","").putLong("processed",0).putLong("passed5",0).putLong("passed10",0).putInt("bestGame",0).putLong("bestScore",Long.MIN_VALUE).putLong("startedAt",System.currentTimeMillis()).apply();}if(!worker&&sp.getBoolean("running",false)){startForeground(71,note("Preparando análise...",0));worker=true;new Thread(this::work,"Perimetro11Worker").start();}return START_STICKY;}
 private List<Integer> load(String u)throws Exception{try(InputStream in=getContentResolver().openInputStream(Uri.parse(u))){if(in==null)throw new FileNotFoundException("Não foi possível reabrir o TXT.");return Engine.parseHistory(in);}}
 private void work(){SharedPreferences sp=getSharedPreferences(PREF,MODE_PRIVATE);try{List<Integer> h=load(sp.getString("uri",""));int rep=sp.getInt("repeats",-1);long started=sp.getLong("startedAt",System.currentTimeMillis());Engine.Candidate c=Engine.analyze(h,rep,sp.getLong("processed",0),sp.getLong("passed5",0),sp.getLong("passed10",0),sp.getInt("bestGame",0),sp.getLong("bestScore",Long.MIN_VALUE),(done,total,p5,p10,best)->{double pct=100.0*done/Math.max(1,total);long el=Math.max(1,System.currentTimeMillis()-started);long eta=pct>.1?(long)(el*(100.0/pct-1.0)):-1;SharedPreferences.Editor e=sp.edit().putLong("processed",done).putLong("passed5",p5).putLong("passed10",p10).putFloat("pct",(float)pct).putLong("elapsed",el).putLong("eta",eta).putString("msg",rep+" repetidas — "+done+"/"+total+" | perímetro="+p5+" | ranking="+p10);if(best!=null)e.putInt("bestGame",best.game).putLong("bestScore",best.score);e.apply();notifyNow(rep+" repetidas • "+String.format(Locale.US,"%.1f%%",pct),(int)pct);});String report=Engine.report(c,h,sp.getLong("passed5",0),sp.getLong("passed10",0));sp.edit().putBoolean("running",false).putBoolean("done",true).putFloat("pct",100).putLong("eta",0).putString("msg","Concluído").putString("report",report).apply();notifyNow("Análise concluída — "+rep+" repetidas",100);}catch(Throwable e){sp.edit().putBoolean("running",false).putString("error",e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage())).apply();notifyNow("Erro na análise",0);}finally{worker=false;try{if(Build.VERSION.SDK_INT>=24)stopForeground(STOP_FOREGROUND_DETACH);else stopForeground(false);}catch(Exception ignored){}}}
 @Override public IBinder onBind(Intent i){return null;}
}
