package br.com.lotofacil.perimetro11;
import java.io.*; import java.util.*; import java.util.regex.*;
public final class Engine {
 private Engine(){}
 public static final class Candidate { public final int game,repeats; public final int[] p5,p10; public final long score; Candidate(int g,int r,int[] a,int[] b,long s){game=g;repeats=r;p5=a;p10=b;score=s;} }
 public interface Progress { void update(long done,long total,long passed5,long passed10,Candidate best); }
 public static int mask(Collection<Integer> xs){int m=0;for(int n:xs)if(n>=1&&n<=25)m|=1<<(n-1);return m;}
 public static int hits(int a,int b){return Integer.bitCount(a&b);} public static String fmt(int m){StringBuilder s=new StringBuilder();for(int n=1;n<=25;n++)if((m&(1<<(n-1)))!=0){if(s.length()>0)s.append(" ");s.append(String.format(Locale.US,"%02d",n));}return s.toString();}
 static boolean valid15(List<Integer> v,int st){if(st<0||st+15>v.size())return false;boolean[] seen=new boolean[26];for(int i=0;i<15;i++){int n=v.get(st+i);if(n<1||n>25||seen[n])return false;seen[n]=true;}return true;}
 public static List<Integer> parseHistory(InputStream in)throws IOException{BufferedReader br=new BufferedReader(new InputStreamReader(in,"UTF-8"));ArrayList<Integer> out=new ArrayList<>();Pattern p=Pattern.compile("\\d+");String line;while((line=br.readLine())!=null){Matcher mt=p.matcher(line.replace("\uFEFF",""));ArrayList<Integer> v=new ArrayList<>();while(mt.find())try{v.add(Integer.parseInt(mt.group()));}catch(Exception ignored){}int best=-1;for(int st=v.size()-15;st>=0;st--)if(valid15(v,st)){best=st;break;}if(best>=0){ArrayList<Integer> nums=new ArrayList<>();for(int i=0;i<15;i++)nums.add(v.get(best+i));out.add(mask(nums));}}if(out.size()<20)throw new IOException("Só foram reconhecidos "+out.size()+" concursos válidos.");return out;}
 static int comb(int n,int k){if(k<0||k>n)return 0;long r=1;for(int i=1;i<=k;i++)r=r*(n-k+i)/i;return (int)r;} public static long universeSize(int r){return (long)comb(15,r)*comb(10,15-r);}
 static int[] vals(int m){int[] a=new int[Integer.bitCount(m)];int k=0;for(int n=1;n<=25;n++)if((m&(1<<(n-1)))!=0)a[k++]=n;return a;} static int choose(int[] v,int cm){int m=0;for(int i=0;i<v.length;i++)if((cm&(1<<i))!=0)m|=1<<(v[i]-1);return m;} static int first(int k){return (1<<k)-1;} static int next(int x){int u=x&-x,v=x+u;if(v==0)return -1;return v+(((v^x)/u)>>2);}
 public static int[] previousScores(int game,List<Integer> h,int count){int end=h.size()-1,start=Math.max(0,end-count);int[] out=new int[end-start];int k=0;for(int i=end-1;i>=start;i--)out[k++]=hits(game,h.get(i));return out;}
 public static boolean perimeter5Accept(int[] p5){if(p5.length!=5)return false;boolean has11=false;for(int p:p5){if(p==11)has11=true;if(p>11)return false;}return has11;}
 public static boolean ranking10Accept(int[] p10){for(int p:p10)if(p==15)return false;return true;}
 public static long score10(int[] p10){long s=0;int n11=0,n1214=0,total=0;for(int p:p10){total+=p;switch(p){case 14:s+=4000;n1214++;break;case 13:s+=2500;n1214++;break;case 12:s+=1400;n1214++;break;case 11:s+=1000;n11++;break;case 10:s+=300;break;case 9:s+=100;break;case 8:s+=20;break;default:break;}}return s+n11*1500L+n1214*700L+total*40L;}
 static Candidate better(Candidate a,Candidate b){if(a==null)return b;if(b==null)return a;if(b.score!=a.score)return b.score>a.score?b:a;int aa=0,bb=0;for(int x:a.p5)if(x==11)aa++;for(int x:b.p5)if(x==11)bb++;if(aa!=bb)return bb>aa?b:a;return fmt(b.game).compareTo(fmt(a.game))<0?b:a;}
 public static Candidate analyze(List<Integer> h,int rep,long resume,long pass5,long pass10,int bestGame,long bestScore,Progress pg){if(rep<8||rep>10)throw new IllegalArgumentException("Repetidas deve ser 8, 9 ou 10.");int last=h.get(h.size()-1),fail=((1<<25)-1)^last;int[] a=vals(last),b=vals(fail);int enter=15-rep;long total=universeSize(rep),done=0,p5c=pass5,p10c=pass10,lastEmit=resume;Candidate best=null;if(bestGame!=0)best=new Candidate(bestGame,rep,previousScores(bestGame,h,5),previousScores(bestGame,h,10),bestScore);int km=first(rep);while(km>0&&km<(1<<a.length)){if(Integer.bitCount(km)==rep){int pa=choose(a,km);int em=first(enter);while(em>0&&em<(1<<b.length)){if(Integer.bitCount(em)==enter){done++;if(done>resume){int game=pa|choose(b,em);int[] p5=previousScores(game,h,5);if(perimeter5Accept(p5)){p5c++;int[] p10=previousScores(game,h,10);if(ranking10Accept(p10)){p10c++;Candidate c=new Candidate(game,rep,p5,p10,score10(p10));best=better(best,c);}}if(pg!=null&&(done==total||done-lastEmit>=2500)){pg.update(done,total,p5c,p10c,best);lastEmit=done;}}}int nx=next(em);if(nx<=em||nx>=(1<<b.length))break;em=nx;}}int nx=next(km);if(nx<=km||nx>=(1<<a.length))break;km=nx;}if(best==null)throw new IllegalStateException("Nenhum candidato passou pelos filtros.");return best;}
 public static String report(Candidate c,List<Integer> h,long p5c,long p10c){int last=h.get(h.size()-1);StringBuilder s=new StringBuilder();s.append("LOTOFÁCIL — PERÍMETRO 11\n\nRepetidas selecionadas: ").append(c.repeats).append("\nUniverso bruto: ").append(universeSize(c.repeats)).append("\nPassaram perímetro 5: ").append(p5c).append("\nPassaram ranking 10: ").append(p10c).append("\n\nÚltimo resultado — somente referência:\n").append(fmt(last)).append("\n\nCANDIDATO AO PRÓXIMO CONCURSO:\n").append(fmt(c.game)).append("\n\nRepetidas do último: ").append(hits(c.game,last)).append("\n\nPERÍMETRO DOS 5 ANTERIORES:\n");for(int i=0;i<c.p5.length;i++){if(i>0)s.append(" - ");s.append(c.p5[i]);}int n11=0;for(int x:c.p5)if(x==11)n11++;s.append("\nQuantidade de 11 exatos nos 5: ").append(n11).append("\nTeto do perímetro: 11\n\nPONTUAÇÃO NOS 10 ANTERIORES:\n");for(int i=0;i<c.p10.length;i++){if(i>0)s.append(" - ");s.append(c.p10[i]);}s.append("\n");for(int p=11;p<=15;p++){int n=0;for(int x:c.p10)if(x==p)n++;s.append(p).append(" pontos: ").append(n).append("\n");}int t=0;for(int x:c.p10)t+=x;s.append("Total de pontos nos 10: ").append(t).append("\nScore: ").append(c.score).append("\n");return s.toString();}
}
