package br.com.lotofacil.perimetro11;
import android.Manifest; import android.app.*; import android.os.*; import android.content.*; import android.content.pm.PackageManager; import android.net.Uri; import android.view.*; import android.widget.*; import java.io.*; import java.util.*;
public class MainActivity extends Activity { final int PURPLE=0xFF6A1B9A; TextView status,prog,out; ProgressBar bar; Button load,b8,b9,b10,reset; Handler h=new Handler(Looper.getMainLooper()); Runnable ticker;
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(dp(10),dp(8),dp(10),dp(8));if(b)v.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);return v;} Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(android.graphics.Color.WHITE);b.setBackgroundColor(PURPLE);return b;}
 @Override public void onCreate(Bundle x){super.onCreate(x);try{ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(12),dp(14),dp(40));sv.addView(r);TextView hd=tv("LOTOFÁCIL — PERÍMETRO 11",23,true);hd.setTextColor(android.graphics.Color.WHITE);hd.setBackgroundColor(PURPLE);r.addView(hd);r.addView(tv("Escolha 8, 9 ou 10 repetidas. O último é só referência. O perímetro começa no penúltimo, exige pelo menos um 11 exato e não pode passar de 11.",13,true));load=bt("CARREGAR TXT");r.addView(load,new LinearLayout.LayoutParams(-1,dp(60)));status=tv("Aguardando TXT.",14,true);r.addView(status);bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);r.addView(bar,new LinearLayout.LayoutParams(-1,dp(18)));prog=tv("0,0% | Tempo 00:00 | ETA --:--",13,true);r.addView(prog);b8=bt("ANALISAR 8 REPETIDAS — 772.200");b9=bt("ANALISAR 9 REPETIDAS — 1.051.050");b10=bt("ANALISAR 10 REPETIDAS — 756.756");r.addView(b8,new LinearLayout.LayoutParams(-1,dp(64)));r.addView(b9,new LinearLayout.LayoutParams(-1,dp(64)));r.addView(b10,new LinearLayout.LayoutParams(-1,dp(64)));reset=bt("ZERAR / NOVA ANÁLISE");r.addView(reset,new LinearLayout.LayoutParams(-1,dp(58)));out=tv("",13,false);out.setTextIsSelectable(true);r.addView(out);load.setOnClickListener(v->pick());b8.setOnClickListener(v->start(8));b9.setOnClickListener(v->start(9));b10.setOnClickListener(v->start(10));reset.setOnClickListener(v->reset());setContentView(sv);ticker=()->{refresh();h.postDelayed(ticker,1000);};if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},40);}catch(Throwable e){setContentView(tv("Erro protegido ao abrir: "+e.getMessage(),16,true));}}
 @Override protected void onResume(){super.onResume();if(ticker!=null)h.post(ticker);} @Override protected void onPause(){super.onPause();if(ticker!=null)h.removeCallbacks(ticker);}
 void pick(){SharedPreferences sp=getSharedPreferences(AnalysisService.PREF,MODE_PRIVATE);if(sp.getBoolean("running",false)){Toast.makeText(this,"A análise está rodando. O TXT está protegido.",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/*");startActivityForResult(i,10);}
 @Override protected void onActivityResult(int q,int r,Intent d){super.onActivityResult(q,r,d);if(q!=10||r!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();try(InputStream in=getContentResolver().openInputStream(u)){List<Integer> hist=Engine.parseHistory(in);try{int f=d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);getContentResolver().takePersistableUriPermission(u,f);}catch(Exception ignored){}getSharedPreferences(AnalysisService.PREF,MODE_PRIVATE).edit().clear().putString("uri",u.toString()).putInt("drawCount",hist.size()).apply();status.setText("Concursos válidos carregados: "+hist.size()+" | TXT OK");out.setText("");bar.setProgress(0);}catch(Exception e){status.setText("Erro no TXT: "+e.getMessage());}}
 void start(int rep){SharedPreferences sp=getSharedPreferences(AnalysisService.PREF,MODE_PRIVATE);String uri=sp.getString("uri","");if(uri.isEmpty()){Toast.makeText(this,"Carregue o TXT primeiro.",Toast.LENGTH_LONG).show();return;}if(sp.getBoolean("running",false)){Toast.makeText(this,"Já existe análise em andamento.",Toast.LENGTH_LONG).show();return;}Intent s=new Intent(this,AnalysisService.class);s.setAction("START");s.putExtra("uri",uri);s.putExtra("repeats",rep);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);status.setText("Selecionado: "+rep+" repetidas. Iniciando...");}
 void refresh(){try{SharedPreferences sp=getSharedPreferences(AnalysisService.PREF,MODE_PRIVATE);boolean run=sp.getBoolean("running",false),done=sp.getBoolean("done",false);float p=sp.getFloat("pct",0);long el=sp.getLong("elapsed",0),eta=sp.getLong("eta",-1);bar.setProgress((int)(Math.max(0,Math.min(100,p))*10));prog.setText(String.format(Locale.US,"%.1f",p).replace('.',',')+"% | Tempo "+fmt(el)+" | ETA "+(eta<0?"--:--":fmt(eta)));if(run)status.setText(sp.getString("msg","Analisando..."));else if(done)status.setText("Análise concluída.");else if(!sp.getString("error","").isEmpty())status.setText("Erro: "+sp.getString("error",""));out.setText(sp.getString("report",""));load.setEnabled(!run);b8.setEnabled(!run);b9.setEnabled(!run);b10.setEnabled(!run);reset.setEnabled(!run);}catch(Throwable e){status.setText("Estado salvo ignorado com segurança.");}}
 String fmt(long ms){long s=Math.max(0,ms/1000),m=s/60;s%=60;return String.format(Locale.US,"%02d:%02d",m,s);} void reset(){SharedPreferences sp=getSharedPreferences(AnalysisService.PREF,MODE_PRIVATE);if(sp.getBoolean("running",false)){Toast.makeText(this,"A análise está rodando. O checkpoint está protegido.",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("Zerar análise?").setMessage("Apaga progresso e resultado, mas mantém o TXT.").setNegativeButton("Cancelar",null).setPositiveButton("ZERAR",(d,w)->{String uri=sp.getString("uri","");int c=sp.getInt("drawCount",0);sp.edit().clear().putString("uri",uri).putInt("drawCount",c).apply();out.setText("");bar.setProgress(0);prog.setText("0,0% | Tempo 00:00 | ETA --:--");status.setText("Pronto para nova análise.");}).show();}
}
